# Introduction

In a flipped classroom environment, all material on key content is made available to students to read and/or watch at their own pace at home. Face-to-face time with lecturers is then reserved for learning consolidation and identifying and addressing specific difficulties through 'active learning' exercises such as problem solving and discussion.

Although the "at-home" learning experience in flipped classroom environments can be implemented using readings or audio podcasts, research suggests students are more likely to engage with and absorb the material when it is provided in video form. For example, @Halyo2013 found that students prefer watching videos to reading about the same material in a textbook. @Kao2008 used video podcasts in an engineering classroom setting; a follow-up survey of students' perceptions suggested that the vast majority found them helpful, especially because they allowed them to revisit the lectures when completing homework assignments. Other studies have reached similar conclusions [see *e.g.*, @Beatty2019; @Intani2013].

Evidence also suggests that allowing students to view videos at home in their own time improved student learning. For example, in the study by @Halyo2013, students were allocated into one of two types of classes: one in which they were asked to review a video during class and then engage in an active learning exercise and another where students reviewed the video at home before class. According to a perception survey, students would watch the video in more circumstances than would be possible from attending a classroom lecture. In a follow up study of the use of online video lectures in a more advanced course, @Halyo2013 also found that students particularly liked how watching video lectures before class freed up class time for problem solving interactively with the instructor. @Caviglia-Harris2016 investigated how using videos in a flipped learning environment impacted students' grades in an introductory microeconomics course. She found students in the flipped learning environment did significantly better on the final exam than students in an otherwise identical course that employed "traditional" lecture-based teaching methods.

Although evidence has consistently shown that pre-recorded lectures can be an effective means of enhancing the learning experience in a flipped classroom environment, it is also not the case that all videos are created equal. In a large scale study of video engagement, @Guo2014 found that shorter videos, videos with talking heads and those that use Kahn-style tablet drawings are more engaging than providing voice-recordings over slides and even high quality pre-recorded classroom lectures.^["Kahn-style tablet drawings" refer to the type of videos made popular by Sal Kahn of [KahnAcademy.org](https://www.khanacademy.org/).] (Similar results have been documented in subsequent studies [see *e.g.*, @Beatty2016].) @Yu2021 found that having the teacher present in a video significantly improved students' academic achievement. Students reported especially liking how videos with the teacher's face on-screen made the learning experience resemble a live classroom setting.

Using lightboards in pre-recorded lectures permits Kahn-style tablet drawings *and* enables students to view the lecturer's head. Moreover, given writing space limitations on a lightboard---combined with the fact that it is more difficult to erase lightboards than it is to clear traditional whiteboards and chalkboards---it also encourages the content creator to cover a smaller amount of material and therefore create shorter videos.

So what *is* a lightboard? A lightboard is a sheet of glass illuminated by light that, when written on using florescent pens, makes writing glow (see the left-hand Figure \@ref(fig:lightboard)). The lightboard allows the lecturer to combine a "chalk-and-talk" experience while simultaneously facing his audience. It is therefore thought to encourage more discussion and familiarity and make students more willing to participate in the learning experience, especially in a flipped classroom environment.

Given the lightboard is a relatively new technology, literature on its use and evaluation in flipped classroom environments is limited. @Smith2017 assessed the impact of lightboard videos on students' perceptions of learning in a nutrition course. The qualitative feedback they analysed suggested that students found the lightboard videos more engaging and perceived having achieved a greater understanding of the material when they were used. @Rogers2019 intentionally interspersed lightboard videos with normal lectures in an undergraduate civil engineering course. They found students' performance on a weekly quiz was higher when they were exposed to lightboard videos as opposed to traditional face-to-face lectures. In an end-of-semester survey, students also reported finding the videos helpful for understanding and engaging with the material; lightboard videos were also associated with higher scores on overall student satisfaction. Other studies have found positive outcomes when students were asked to complete an assignment using the lightboard [@Hite2019].

A number of case studies exist describing the use and implementation of lightboards in specific contexts. For example, @Fung2017 describes a small-scale pilot implementation of the lightboard in an introductory chemistry course taught at the National University of Singapore. @Ye2016 discusses its implementation in the context of Chinese language instruction and provides a particularly detailed overview of the set-up required and the advantages and disadvantages of the technology.  @McCorkle2020 present a detailed case study of small-scale lightboard pilot and full-scale lightboard build with accompanying studio used by a variety of faculties at a small, private liberal arts college in the U.S.

The purpose of this study is to build on this emerging literature describing student perceptions about and case study implementations of an "at-home" lightboard with accompanying recording studio for an advanced undergraduate economics course held between October 2020 and January 2021. It is believed that the results of this study will be particularly useful to educators looking to implement a flipped classroom environment while dealing with the stay-at-home requirements imposed by the COVID-19 pandemic.

The paper proceeds in the following order. Section \@ref(case-study) describes a small-scale lightboard (with accompanying at-home studio) pilot and build for a third-year undergraduate economics course taught at the University of Liverpool during the first term of the 2020–2021 academic year. Section \@ref(feedback) discusses the implementation of and results from a perception survey distributed to students at the end of the course. Section \@ref(discussion) concludes by identifying the advantages and disadvantages of incorporating the lightboard in a flipped classroom environment, particularly given stay-at-home requirements imposed by the COVID-19 pandemic. It also discusses several best practices the author identified while building and incorporating the lightboard into her flipped classroom learning environment.
