# Discussion

## Advantages and disadvantages of the lightboard

The lightboard has several advantages to recommend it to instructors looking to re-create their lectures in the face of COVID-19-related lockdown rules. The primary advantage is that, beyond the cost of designing the lecture, creating lightboard videos requires very little technical expertise and labour---and almost none if you video-record lectures through a mirror. This means that the marginal cost of creating additional videos is very low, and therefore makes it an ideal solution for lecturers who have to create many videos in a short amount of time.

One of the big (personal) drawbacks I have found in having to pre-record lectures is that it is more difficult to sound enthusiastic without the presence of a live student audience. This is an important factor given studies show lecturer enthusiasm correlates positively with student evaluations [see *e.g.*, @Murray1983; @Lindsay2002]. Nevertheless, I found the novelty of creating videos with a lightboard made me more enthusiastic during recording sessions and that enthusiasm partially or even wholly compensated for what I must have lost from no longer having a live audience to react to.

There are several other benefits to the lightboard technology that recommend it for more general adoption even after the COVID-19-related stay-at-home orders are relaxed. First, the lightboard allows the lecturer to face the audience. This is thought to foster a more engaging and interactive experience with students [see *e.g.*, @Guo2014]. As discussed in @Ye2016, the lightboard requires that student engage their auditory and visual working memory simultaneously, which may increase working memory capacity more than using each in isolation [@Mayer1998] and the combination of audio and hand gestures may be especially effective [@Kelly2008]. A recent study by @Yu2021 also found that being able to see the teacher in a video improved students' academic achievement.

Nevertheless, the lightboard is not appropriate in all circumstances. First and foremost, the lightboard is obviously not very relevant for courses that wouldn't use the whiteboard or chalkboard anyway---*e.g.*, courses which use very little maths or few diagrams. In this instance, the cost of building the lightboard and accompanying studio is unlikely to be justified by the benefits.

A second, related disadvantage is that lightboards are not trivial---or necessarily inexpensive---to build. In my own case, I had to purchase a router; I already owned a table saw, but if you do not, you may have to buy that as well. Indeed, as illustrated in Table \@ref(tab:lightboard-costs) the total cost of simply building a lightboard came to \textsterling 253.03; after adding in the cost of setting up the recording studio and buying video editing software, I have spent almost \textsterling 800 on the entire project. Moreover, building a lightboard requires, at a minimum, a basic familiarity with carpentry (*e.g.*, knowing how to use a router to recess a channel in the wooden frame to hold the glass). Depending on the thickness of the glass used, one may also need more than one person to help construct the lightboard and, in particular, position the glass properly into the wooden frame.^[Having said this, there are several much easier and less expensive methods of building a lightboard that work almost as well---and result in videos that look just as professional---as the lightboard I built. For example, instead of using glass and building a wooden frame, one can simply attach LED lights around the perimeter of plexiglass using clamps (see, for example, [Elisa Valkyria](https://www.youtube.com/watch?v=L1au1JxMSaA "How to build your own lightboard")'s tutorial).]

The third and fourth drawbacks of the lightboard are that it: (i) requires the instructor to carefully plan the lecture in advance; and (ii) is not practical for long videos. The fundamental issue behind both drawbacks is that there is only so much "real estate" on a lightboard available for writing. So if the video lasts longer than 5–10 minutes, then the instructor will likely have to clean the board while he is in the middle of filming—and cleaning a lightboard is a much more time consuming task than erasing a whiteboard or chalkboard. Although a small amount of post-production editing---*e.g.*, cutting out the period when the instructor is cleaning the board or simply speeding it up---can eliminate this inconvenience for students, doing so may require more video editing skill than some users are willing to spend the time to obtain.

Finally, lightboards are impractical for most live classroom settings and even synchronous online events. The difficulty comes from having to flip the instructor's handwriting in real time. Although some professional lightboard setups exist that will do this---thus allowing a live audience to experience the presenter's writing in reverse---they are not cheap. Figures in @Ye2016 suggest they cost upwards of $10,000.

## Best practice

Due to COVID-19, a significant portion of instruction in higher education has moved away from the traditional front-of-class lecture model to an active learning environment. In this paper, I have described how and why I adopted a lightboard to facilitate this. Based on my experience implementing the case study and the results of the student perception survey, I have identified the following best practices in integrating the lightboard into an "at home" flipped learning environment. 

1. **Use plexiglass**. Having used 10mm safety glass myself, I can confidently say that if I were rebuilding my lightboard, I would simply use plexiglass. Although glass is clearer than plexiglass, it comes with several disadvantages. First, 3mm picture glass is cheap and can be easily purchased from a picture framer but easily breaks. Thicker toughened glass is the safer option, but it is also substantially more expensive, extremely heavy and must be sourced from a speciality retailer. Plexiglass, on the other hand, is lightweight, cheap and can be easily purchased from your local hardware store. While plexiglass does scratch more easily than glass, they can be easily removed by adjusting the exposure post-production.

2. **Film at night**. Lightboard videos look best if they are filmed against a black backdrop and the only light in the room is from the lightboard and optionally lights specially set up to illuminate the person speaking. Unfortunately, my own home has lots of windows. Instead of blacking out all of the windows in the room where I recorded the videos, I chose to film most videos at night. Early birds and night owls—or those (like me) who live closer to a pole and are filming in winter—may find this option similarly appealing. It also has the added benefit of making the recording studio much easier to quickly take-down and re-assemble, which will be attractive to those who film their vidoes in rooms that also serve other purposes (*e.g.*, a bedroom).

3. **Invest in professional lighting**. Basic lighting using anglepoise lamps work fine, especially when combined with a small investment in the post-production effort required to remove shadows, glare and scratches. The best setups, however, use professional lighting including LED studio lights---with barn doors to make the backdrop completely black---on each side of the lightboard, and a "hair light" to the top of the lightboard to illuminate the speaker's face.

4. **Buy a DSLR camera**. Although you don't need a DSLR camera, careful selection of the shutter speed and aperture will reduce smudges and, especially, increase the contrast with the colour. (And keep in mind that without these controls, viewers will have a hard time distinguishing between colours.)

5. **Employ basic video editing**. Invest a small amount of time in learning how to do a limited number of video editing tasks---*e.g.*, "fast-forwarding" wiping the board, add an intro and apply a sound compressor. Each activity requires very little skill and only a minimal amount of time investment post-production to implement. But they will take your lightboard videos from zero to hero---a little bit of polish goes a long way. I got more emails from students complementing me on the intros I made for each video than I did on the content than was in them!

6. **Structure content into week-by-week chunks**. I initially decided to distribute the course content on a module-by-module basis (*i.e.*, all material on module 1 was released at the same time; then all material on module 2, *etc.*). The idea was that students could then decide when and how to watch, read and complete the content in each module; the only guidance I gave was the date all of the work for a particular module should be completed. While some students adapted well to this approach, others struggled. I therefore eventually created a more detailed (and optional) syllabus that identified exactly which videos, texts and problems students should complete each week. I found this small addition to my course helped several students who had difficulty organising their time without more detailed guidance from me.

7. **Paint the lightboard frame black**. I did not paint the frame around my lightboard, so to make the entire background of the video black, I cropped the videos just at the point where the frame met the glass. Unfortunately, in a small number of instances I accidentally cropped out too much---and consequently deleted a small portion of something I had written on the board. To avoid this in the future while maintaining a perfectly black background, I have since painted the frame around my lightboard black. As long as a video is only cropped at a point outside of the inner edge of the frame, I won't accidentally delete anything I've written on the board; meanwhile, the uncropped black frame is indistinguishable from the black background after adjusting the video's exposure post-production.
