# Conclusions

This study has described a small-scale lightboard pilot and build with accompanying at-home studio for an advanced undergraduate economic theory course taught at the University of Liverpool during the first term of the 2020--21 academic year. My experience with the lightboard over the past year has been very positive. I find the technology relatively easy to create and exceedingly easy to use once the lightboard is built and studio is set up---indeed, I have found that it drastically facilitated creating a large number of videos in a relatively short amount of time. Importantly, it has also allowed me recreate my "chalk-and-talk" lectures while having to teach remotely during the COVID-19 pandemic. Both factors have made the process of adapting to the constraints imposed by the virus more efficient and less time consuming. Students have found the videos engaging and useful for understanding, especially as they allow me to face the audience as I write out derivations and work through examples. I plan to continue incorporating the lightboard into my teaching for at least as long as COVID-19 restrictions remain in place---and likely beyond!